### ISSUE TITLE
error using

### ISSUE THREAD

**Issue by Hosseinyzr** [tuarua/LibAVANE-Android#2]
Hi,
I used this library in android studio project as  module.
when i want to build and install I faced this error:
"Error:error: 'C:/Users/Hossein/Desktop/LibAVANE-Android-master/MyffmpegModuleTest/LibAVANE-Android-master/dist/boost/boost_1_53_0/armeabi-v7a/lib/libboost_system-gcc-mt-1_53.a', needed by 'C:/Users/Hossein/Desktop/LibAVANE-Android-master/MyffmpegModuleTest/LibAVANE-Android-master/build/intermediates/cmake/debug/obj/armeabi-v7a/libavane-lib.so', missing and no known rule to make it"

**Comment by tuarua** [comment]
You also need to check out the 2 git submodules

https://github.com/tuarua/LibAVANE-Android/tree/master/dist

**Comment by Hosseinyzr** [comment]
@tuarua  Thanks... It Worked...
...
but some commands for example overlay filter dint work. how can we fix it?
and i think it would be a favor if you put latest and completed ffmpeg project bulid into this project.
any way thanks to your repository

**Comment by tuarua** [comment]
I have no immediate plans to update.
It was incredibly complex to get this version working, 10+ hours.
I have moved away from using FFmpeg on Android so would need to be paid for carrying out any further work on this.

**Comment by tuarua** [comment]
Closing as you seem to be opening many issues across multiple FFmpeg based repos.
